# Generated by Django 2.1.2 on 2018-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='maint_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='misc_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
