# Generated by Django 2.1.2 on 2018-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_auto_20181006_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='billing',
            name='maint_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
