# Generated by Django 2.1.2 on 2018-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20181006_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=4)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], default='open', max_length=5)),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-job_date',),
            },
        ),
    ]
