# Generated by Django 2.1.2 on 2018-10-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_auto_20181007_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='misc_cost',
        ),
    ]
